import CONST_ANIMAL_NAME
import CONST_KINGDOM_NAME
kingdomsEmblem = {
    CONST_KINGDOM_NAME.SPACE: CONST_ANIMAL_NAME.GORILLA,
    CONST_KINGDOM_NAME.LAND: CONST_ANIMAL_NAME.PANDA,
    CONST_KINGDOM_NAME.WATER: CONST_ANIMAL_NAME.OCTOPUS,
    CONST_KINGDOM_NAME.ICE: CONST_ANIMAL_NAME.MAMMOTH,
    CONST_KINGDOM_NAME.AIR: CONST_ANIMAL_NAME.OWL,
    CONST_KINGDOM_NAME.FIRE: CONST_ANIMAL_NAME.DRAGON,
}